### ISSUE TITLE
TypeError in the HillClimbSearch (tutorial notebook 10)

### ISSUE THREAD

**Issue by yuanjian24** [pgmpy/pgmpy_notebook#53]
In the Notebook '10. Learning Bayesian Networks from Data`

I Encounte the Type error while implementing 

```
hc = HillClimbSearch(data, scoring_method=BicScore(data))
```
![image](https://user-images.githubusercontent.com/50770426/167385139-7c1271e4-35ba-4bc5-b8a3-0bb532e8351c.png)

If I remove `scoring_method=BicScore(data)`, this function works well but the result is inconsistent with the given one. 

Is there any update on this function? Thanks

**Comment by ankurankan** [comment]
@yuanjian24 The `scoring_method` argument has been moved to the `estimate` method from the init method so that you can try out different scoring methods without creating a new `HillClimbSearch` object. There were some other errors in the notebook because of it being old, I have fixed those as well and you should be able to run all the code.
